### ISSUE TITLE
feat: indicate origin of mets and rxns added in recent updates

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/yeast-GEM#161]
Following what we made in PR #156, we should include both in `metNotes` or `rxnNotes` why were the corresponding mets/rxns added for the following past updates to the model:
- [x] **SLIMEr update:** For mets: "pseudo-metabolite part of the SLIMEr formalism (PR #112)". For rxns: "pseudo-reaction part of the SLIMEr formalism (PR #112) - units in mg/gDWh"
- [x] **New annotation update:** For both mets and rxns indicate "added after new annotation (PR #142)"
- [x] **Biolog update:** For both mets and rxns indicate " added after the Biolog update (PR #149)"

For consistency, we should also update the notes added in #156:
- [x] **Metabolomics update:** For mets: "added from metabolomics data (PR #156)". For rxns: "metabolites observed in metabolomics data (PR #156)"

**I hereby confirm that I have:**
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/yeast-GEM) about the issue

**Comment by BenjaSanchez** [comment]
update: this was completed in PR #170, this issue will be closed on next release
